name: Deploy ML Training

on:
  push:
    branches:
      - main
      - test
      - amirbo_feature_branch
    paths:
      - 'examples/analytic-workflow/ml/training/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/smus-direct-deploy.yml
    secrets:
      AWS_ROLE_ARN_TEST: ${{ secrets.AWS_ROLE_ARN_TEST }}
    with:
      manifest_path: 'examples/analytic-workflow/ml/training/manifest.yaml'
      test_target: 'test'
